# Generated by Django 5.0.2 on 2024-02-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='guid',
            field=models.CharField(default='x', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
